//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Com.Eucalyptus.Windows {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://eucalyptus.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://eucalyptus.com", IsNullable=false)]
    public partial class Configuration {
        
        private string hostnameField;
        
        private ConfigurationLocalAccount localAccountField;
        
        private ConfigurationActiveDirectory activeDirectoryField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Hostname {
            get {
                return this.hostnameField;
            }
            set {
                this.hostnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ConfigurationLocalAccount LocalAccount {
            get {
                return this.localAccountField;
            }
            set {
                this.localAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ConfigurationActiveDirectory ActiveDirectory {
            get {
                return this.activeDirectoryField;
            }
            set {
                this.activeDirectoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://eucalyptus.com")]
    public partial class ConfigurationLocalAccount {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://eucalyptus.com")]
    public partial class ConfigurationActiveDirectory {
        
        private bool joinOnBootField;
        
        private bool joinOnBootFieldSpecified;
        
        private string adField;
        
        private string aDUsernameField;
        
        private string aDPasswordField;
        
        private string ouField;
        
        private bool overwriteField;
        
        private bool overwriteFieldSpecified;
        
        /// <remarks/>
        public bool JoinOnBoot {
            get {
                return this.joinOnBootField;
            }
            set {
                this.joinOnBootField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JoinOnBootSpecified {
            get {
                return this.joinOnBootFieldSpecified;
            }
            set {
                this.joinOnBootFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string AD {
            get {
                return this.adField;
            }
            set {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        public string ADUsername {
            get {
                return this.aDUsernameField;
            }
            set {
                this.aDUsernameField = value;
            }
        }
        
        /// <remarks/>
        public string ADPassword {
            get {
                return this.aDPasswordField;
            }
            set {
                this.aDPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OU {
            get {
                return this.ouField;
            }
            set {
                this.ouField = value;
            }
        }
        
        /// <remarks/>
        public bool Overwrite {
            get {
                return this.overwriteField;
            }
            set {
                this.overwriteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OverwriteSpecified {
            get {
                return this.overwriteFieldSpecified;
            }
            set {
                this.overwriteFieldSpecified = value;
            }
        }
    }
}
